# Generated by Django 4.1.3 on 2023-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("OrderId", models.AutoField(primary_key=True, serialize=False)),
                ("UserId", models.CharField(max_length=10)),
                ("PurchaseDate", models.CharField(max_length=20)),
                ("Total", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                ("OrderDetailsId", models.AutoField(primary_key=True, serialize=False)),
                ("OrderId", models.CharField(max_length=10)),
                ("ProductId", models.CharField(max_length=10)),
                ("Title", models.CharField(max_length=50)),
                ("Description", models.CharField(blank=True, max_length=500)),
                ("Price", models.CharField(max_length=10)),
                ("Image", models.CharField(max_length=1000)),
                ("Quantity", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "ProductId",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Title", models.CharField(max_length=50)),
                ("Description", models.CharField(blank=True, max_length=500)),
                ("Price", models.CharField(max_length=10)),
                ("Stock", models.CharField(max_length=10)),
                ("Category", models.CharField(max_length=20)),
                ("Image", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SCart",
            fields=[
                ("CartId", models.AutoField(primary_key=True, serialize=False)),
                ("UserId", models.CharField(max_length=10)),
                ("ProductId", models.CharField(max_length=10)),
                ("Quantity", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "UserId",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("birthday", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("postalcode", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("photoId", models.CharField(max_length=500)),
                ("webcamPhoto", models.CharField(max_length=500)),
            ],
        ),
    ]
