# Generated by Django 4.1.3 on 2023-01-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductId", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=50)),
                ("Description", models.CharField(blank=True, max_length=500)),
                ("Price", models.CharField(max_length=10)),
                ("Stock", models.CharField(max_length=10)),
                ("Image", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("birthday", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("postalcode", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
