# Generated by Django 4.1.3 on 2023-02-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amtranspo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="Quantity",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
