# Generated by Django 4.1.3 on 2023-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amtranspo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCart",
            fields=[
                ("CartId", models.AutoField(primary_key=True, serialize=False)),
                ("UserId", models.CharField(max_length=10)),
                ("ProductId", models.CharField(max_length=10)),
                ("Quantity", models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(name="Cart",),
    ]
